baseURL = 'https://coagulate.social/'
title = 'Coagulate'
disableKinds = ['taxonomy', 'term']
enableRobotsTXT = true

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false
[languages]
  [languages.en]
    contentDir = 'content/en'
    disabled = false
    languageDirection = 'ltr'
    languageName = 'English'
    weight = 1
    [languages.en.params]
      subtitle = 'Reference, Tutorials, and Explanations'
  [languages.de]
    contentDir = 'content/de'
    disabled = false
    languageCode = 'de-DE'
    languageDirection = 'ltr'
    languageName = 'Deutsch'
    weight = 2
    [languages.de.params]
      subtitle = 'Referenz, Tutorials und Erklärungen'

[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
