baseURL = 'https://coagulate.social/'
title = 'Coagulate'
disableKinds = ['taxonomy', 'term']
enableRobotsTXT = true

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false
[languages]
  [languages.en]
    contentDir = 'content/en'
    disabled = false
    languageDirection = 'ltr'
    languageName = 'English'
    weight = 1
    [languages.en.params]
      subtitle = 'Contact details & location sharing, securely.'
  [languages.de]
    contentDir = 'content/de'
    disabled = true
    languageCode = 'de-DE'
    languageDirection = 'ltr'
    languageName = 'Deutsch'
    weight = 2
    [languages.de.params]
      subtitle = 'Kontaktdaten & Aufenthaltsorte teilen, sicher.'

[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
