baseURL = 'https://coagulate.social/'
title = 'Coagulate'
disableKinds = ['taxonomy', 'term']

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true
[languages]
  [languages.en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    weight = 1
    [languages.en.params]
      subtitle = 'Reference, Tutorials, and Explanations'
  [languages.de]
    contentDir = 'content/de'
    disabled = false
    languageCode = 'de-DE'
    languageDirection = 'ltr'
    languageName = 'Deutsch'
    weight = 2
    [languages.de.params]
      subtitle = 'Referenz, Tutorials und Erklärungen'
