top:
- name: Roadmap
  pageRef: /roadmap
  weight: 10
- name: Contribute
  pageRef: /contribute
  weight: 20
- name: Compare
  pageRef: /compare
  weight: 30
- name: Donate
  pageRef: /donate
  weight: 40