on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    # Once per day at 12:00 AM
    - cron:  '0 0 * * *'

jobs:
  check-broken-links:
    runs-on: ubuntu-22.04
    container: ubuntu:latest
    steps:
      - name: Install wget
        run: apt update && apt install -y -qq wget
      - uses: actions/checkout@v3
      - name: Check EN
        if: always()
        shell: bash
        run: ./check_broken_links.sh https://coagulate.social/en/
      - name: Check DE
        if: always()
        shell: bash
        run: ./check_broken_links.sh https://coagulate.social/de/
